### PR TITLE
[BE] Data Retrieval 

### PR DESCRIPTION
**Pull request by jumaallan**
This is a WIP PR

### CODE REVIEW

**Comment by codecakes** [comment]
@jumaallan we'll need to test whether the client app is registered on my firebase account

**Review by codecakes — COMMENTED** [review]
Use smart commits if you are working on a jira user story: https://support.atlassian.com/bitbucket-cloud/docs/use-smart-commits/

**Comment by jumaallan** [comment]
> Use smart commits if you are working on a jira user story: https://support.atlassian.com/bitbucket-cloud/docs/use-smart-commits/

thanks

**Comment by codecakes** [comment]
> @jumaallan @codecakes is this ready? it looks like only the setup was done, not sure that was all the scope for the ticket

@jumaallan ping when u r free, we can verify the client app registered on firebasel

**Comment by jumaallan** [comment]
We wanted to merge to develop - then I'll repick from there

**Pull request merged**
